/**
 * GENERATED by `node scripts/build/stamp-stylesheet.mjs` — do not edit.
 *
 * A content hash of app/globals.css. The same value is written into the
 * stylesheet as `--stylesheet-build`; `StylesheetGuard` compares the two in
 * development and complains loudly when a browser is rendering fresh HTML
 * against a stale stylesheet. See Revision 23 §2.
 */
export const STYLESHEET_BUILD = "1d8a958924fd";
