/**
 * GENERATED by `node scripts/build/check-cover.mjs` — do not edit.
 *
 * The bridge between `data/cover.ts`, which knows ids, and the cover
 * components, which need a src and intrinsic dimensions. Regenerate after
 * adding, removing or replacing anything in `public/cover/`; the same script
 * run with --check fails if this file has drifted from what is on disk.
 */
export type CoverFile = { src: string; w?: number; h?: number };

export const coverFiles: Record<string, { landscape: CoverFile; portrait: CoverFile }> = {
  "01": {
    landscape: {"src":"/cover/landscape/01.jpg","h":657,"w":980},
    portrait: {"src":"/cover/portrait/01.jpg","h":1104,"w":736},
  },
  "02": {
    landscape: {"src":"/cover/landscape/02.jpg","h":492,"w":750},
    portrait: {"src":"/cover/portrait/02.jpg","h":1104,"w":736},
  },
  "03": {
    landscape: {"src":"/cover/landscape/03.jpg","h":460,"w":735},
    portrait: {"src":"/cover/portrait/03.jpg","h":1788,"w":1199},
  },
};
