/**
 * THE ROTATION SECTION'S BACKGROUND PHOTOGRAPH — Revision 20 §4.
 *
 * To change it: replace the file(s) in `public/rotation/`, then update the
 * numbers below. Nothing else in the codebase contains these paths, and
 * `npm run check:rotation-image` fails the build if a declared file is missing
 * or if its dimensions here disagree with the file on disk.
 *
 * ---------------------------------------------------------------------------
 * WHAT THIS REPLACES
 *
 * Revision 16's cut-out figure — a transparent PNG of a person, matted against
 * the section ground, with AVIF and WebP derivatives generated by a build
 * script. Revision 20 retires it on every breakpoint: the section is now a full
 * photograph behind the type, at both sizes.
 *
 * `public/rotation/figure.png` and its two derivatives are STILL ON DISK and
 * are no longer referenced by anything. They are left there deliberately rather
 * than deleted, so the decision to throw away the artwork is the owner's.
 * Nothing downloads them.
 * ---------------------------------------------------------------------------
 *
 * ON THE IMAGE ITSELF: if the subject is an identifiable real person, it must
 * be your own shoot or properly licensed WITH A RELEASE. This is a commercial
 * site, and a portrait is not stock the way a landscape is.
 */
export type RotationSource = {
  src: string;
  /** The file's TRUE pixel dimensions — these hold CLS at zero. */
  width: number;
  height: number;
};

/** A source that is `object-fit: cover`-ed behind the type. Mobile only. */
export type RotationCoverSource = RotationSource & {
  /**
   * `object-position`. The photograph is `object-fit: cover` behind the type,
   * so on a viewport whose shape does not match the file's this is what decides
   * which part survives — and, specifically, whether the subject's face does.
   */
  focal: string;
};

/**
 * THE VINYL RECORD, MEASURED FROM THE FILE — Revision 21 §2.
 *
 * All four numbers are percentages of the image's own dimensions, so they hold
 * at any rendered size. `cx` and `labelR`/`discR` are percentages of the
 * WIDTH; `cy` is a percentage of the HEIGHT.
 *
 * They were measured by `scripts/visual/_measure-disc.mjs`, not by eye, and
 * three naive measurements failed first — each failure being a fact about this
 * particular illustration:
 *
 *   1. Masking on DARKNESS split every column through the white label into two
 *      half-chords and put the centre 94px out.
 *   2. Masking on NOT-THE-GROUND fixed that, but the leftmost usable column was
 *      a music note, and one bad column in a two-point fit is the whole fit.
 *   3. Fitting a circle to the record's visible left arc converged beautifully
 *      — mean residual 0.88px — on the WRONG CIRCLE. A short arc is badly
 *      conditioned, and the answer it gave put the centre 41px left of the
 *      spindle hole.
 *
 * What finally worked: the label is a full circle in the frame, so its centre
 * and radius come from the bright region's chord heights, and the disc's radius
 * is then the distance from that centre to the record's outer edge, read along
 * rows near the top of the frame where the grooves are unbroken by the
 * highlight. Five independent rows agreed to within 0.3px.
 *
 * Verify any change with `node scripts/visual/_measure-disc.mjs`, which also
 * writes an overlay to check by eye.
 */
export type RotationDisc = {
  /** Record centre, % of image width. */
  cx: number;
  /** Record centre, % of image height. */
  cy: number;
  /** White label radius, % of image width. */
  labelR: number;
  /** Whole disc radius, % of image width. */
  discR: number;
};

export type RotationDesktopSource = RotationSource & {
  disc: RotationDisc;
  /** The flat grey sampled from the image's left edge. */
  ground: string;
};

export type RotationVisual = {
  /** Phones, below 768px: the full-bleed photograph. Unchanged by Revision 21. */
  mobile: RotationCoverSource;
  /** Laptops and desktops, 768px and up: the vinyl illustration. */
  desktop: RotationDesktopSource;
  /** Decorative: the section's own text carries the meaning. */
  alt: string;
};

export const rotationVisual: RotationVisual = {
  mobile: {
    src: "/rotation/image.jpg",
    width: 820,
    height: 1024,
    /*
      The subject's face sits high and slightly left — roughly x 25-50%,
      y 12-40% of the frame. A phone viewport is TALLER than 4:5, so `cover`
      crops the SIDES and the vertical value does nothing here; 45% horizontally
      keeps her centred in what is left rather than drifting to the right edge.
    */
    focal: "45% 50%",
  },

  desktop: {
    src: "/rotation/image2.jpg",
    width: 626,
    height: 357,
    disc: { cx: 97.236, cy: 49.3, labelR: 8.898, discR: 29.137 },
    /*
      Sampled as the median of a 30px strip down the far left, which the music
      notes do not reach. A median rather than a mean so that one stray dark
      pixel cannot pull it.

      THIS EXACT VALUE IS WHY ALL SMALL TEXT ON DESKTOP IS --bone. #5A5A5A is a
      mid grey, not a dark ground: --bone reaches 5.60 on it, --tan 3.53 (large
      text only) and --bone-2 just 3.18, which fails. See §3's table.
    */
    ground: "#5a5a5a",
  },

  /**
   * Empty, deliberately. The images carry no information the surrounding text
   * does not already give — the volume, the dates, the track count, the two
   * section names and the button are all real text — so to a screen reader they
   * are decoration, and describing them would only add noise between the meta
   * block and the links.
   */
  alt: "",
};

/**
 * WHY THERE IS NO `rotationDesktop` FALLBACK ANY MORE.
 *
 * Revision 20 had one, because there was no desktop file and both <source>s
 * pointed at the phone's photograph. Revision 21 supplies a real second image,
 * so the fallback has nothing to fall back to and is gone rather than left
 * resolving to itself.
 */

export default rotationVisual;
